### PR TITLE
implement Internationalization of comments/tooltips

### PR DESCRIPTION
**Pull request by mrdengbo**
Support tooltips internationalization in the GUI configuration tool

### CODE REVIEW

**Comment by mrdengbo** [comment]
1. I have realized the internationalization of comments/tooltips, but currently only the Chinese language has been added. It is eagerly hoped that other developments will complement other languages so that internationalization can be realized.The Chinese display is as follows:
image

2. The translation may be inaccurate in some places, and it will be gradually optimized in the later stage, and other developers are also expected to participate in the optimization.

**Comment by rickysarraf** [comment]
Thank you for contributing the localization enhancements.

**Comment by rickysarraf** [comment]
Sorry. I have had to revert this change. But my intent is to have it in but after a closer review.

**Comment by rickysarraf** [comment]
> Sorry. I have had to revert this change. But my intent is to have it in but after a closer review.

I've reintroduced it. Whatever the issues are, I'll try to propose a change. But overall your changes were nice, which is why I added them in the first place. Sorry for the noise againn.

**Pull request merged**
